### ISSUE TITLE
cant specify the gams executable path - mac

### ISSUE THREAD

**Issue by samarthiith** [chrispahm/linter-gams#25]
Hi!
thanks for this package. 
I am not able to specify gams path when running on a mac. The option doesn't appear.
![screen shot 2019-02-22 at 10 19 52 am](https://user-images.githubusercontent.com/9819174/53232458-6c7d0f00-368b-11e9-9252-7186229a9c41.png)

thanks!

**Comment by chrispahm** [comment]
Hey there,
sorry for letting you wait for so long! I also saw your comments in the closed issue, but let's keep it in this new one.
Can you do me a favour and check the following:
Open a new Window in Atom, and in that new window, open the `lib\main.js` file from the linter-gams package. Then, in the Atom menu, click on View -> Developer -> Run Package Specs. Can you tell me what results you are getting there?
Best
Christoph

**Comment by samarthiith** [comment]
hey Christoph,
thanks for the package and reply. Looking forward to using it. 
No worries. Here is the output from the console and elements tab on running package specs:

![image](https://user-images.githubusercontent.com/9819174/53489894-8c993d80-3a92-11e9-828e-7f2b4e5aa9d6.png)
![image](https://user-images.githubusercontent.com/9819174/53489968-bf433600-3a92-11e9-98d0-d9d06e915aed.png)

**Comment by chrispahm** [comment]
Ok, sorry that didn't work as expected :( Atom is now looking for the `spec` in the `lib` folder, where the `spec` file is not located unfortunately. 
Can you do me a favour again, and open a new Terminal window, then enter the following:
```
atom --test --timeout 60 /Users/samarth/.atom/packages/linter-gams/spec/gamsDir-spec.js
```
Once it's done can you paste a screenshot of the output here again? Thanks in advance!
Best
Christoph

**Comment by samarthiith** [comment]
Here it is: 
the gams path seems to be for windows.
![image](https://user-images.githubusercontent.com/9819174/53490763-cff4ab80-3a94-11e9-8991-5923f9e84b37.png)

**Comment by chrispahm** [comment]
Thanks a lot! That already hels a ton. I guess you have `gams` in your PATH variable, is that right? You can check by just entering `gams` in your console. If it doesn't return something like 'Unknown command', then it's in your PATH.

**Comment by samarthiith** [comment]
yeah, it seems to be in my PATH variables.

**Comment by chrispahm** [comment]
ok, then I screwed up at that part. Sorry for that! It seems like the function returns an object in that case (see your terminal output above), where it should return a string...

**Comment by samarthiith** [comment]
haha... no worries. I can imagine how hard it is to get it right for all use cases. let me know when you have fixed it. :)

**Comment by chrispahm** [comment]
Alright, i did a couple of tests, and it *seems* as if the `shell.which` function mistakenly returns an object instead of a string on macOS (works fine on DOS as far as I can tell). Can you do me a favour and replace the `getGamsPath()` function in both `linter-gams` and `gams-helpers` by the following one:

```js
getGamsPath() {
    let gamsExec = shell.which('gams')
    if(gamsExec) {
      if (os.platform() === 'win32') {
        gamsExec = gamsExec.replace(/\\/g, '/')
      }
      return JSON.parse(JSON.stringify(gamsExec))
    }
    // if not found, check in standard directories
    else {
      // in case of windows
      if (os.platform() === 'win32') {
        if (glob.sync('C:/GAMS/*/*/').length > 0) {
          gamsExec = glob.sync('C:/GAMS/*/*/')[glob.sync('C:/GAMS/*/*/').length - 1] + 'gams.exe'
          return gamsExec
        } else if (glob.sync('N:/soft/GAMS*/').length > 0) {
          gamsExec = glob.sync('N:/soft/GAMS*/')[glob.sync('N:/soft/GAMS*/').length - 1] + 'gams.exe'
          return gamsExec
        } else {
          this.alert('noGAMS')
          return ''
        }
      }
      // and mac
      else if (os.platform() === 'darwin') {
        if (glob.sync('/Applications/GAMS*/sysdir/').length > 0) {
          gamsExec = glob.sync('/Applications/GAMS*/sysdir/')[glob.sync('/Applications/GAMS*/sysdir/').length - 1] + 'gams'
          return gamsExec
        } else {
          this.alert('noGAMS')
          return ''
        }
      } else {
        this.alert('noGAMS')
        return ''
      }
    }
  }
```
this is a rather ugly workaround for now, so I opened an issue in the [shell.js](https://github.com/shelljs/shelljs/issues/933) repo to see if there is going to be an official fix.

**Comment by samarthiith** [comment]
it works now! thanks a ton. 
cheers!

**Comment by chrispahm** [comment]
Cool! I will test this workaround on Windows tomorrow and will publish a fix if it works as expected. Please open new issues if anything doesn't work as expected. We mostly use this plugin in our workgroup where I have physical access to the machines, so I never find out if features don't work as they are supposed to in the open 😉

**Comment by chrispahm** [comment]
Alright, I just published the fix in both `linter-gams` and the `gams-helpers` packages. If you could confirm that this patch fixes the issue, I would really appreciate it!

Best
Christoph

**Comment by samarthiith** [comment]
yup! works. 
From quick first impression seems very nice. I am really annoyed with gamside, sudio is better but still no there. 
Let me know if I can be of any help to take this forward. I dont know javascript thou. 

cheers!
Samarth
