### ISSUE TITLE
GAMS View empty

### ISSUE THREAD

**Issue by samarthiith** [chrispahm/linter-gams#33]
Dear Christoph,
thanks for the very useful package. The gams view is being shown inside the settings panel and not in the gams view panel (see image). Any suggestion to correct this? Note: this is a window specific problem, on my mac it seems to working fine. 

Thanks,
Samarth 
![image](https://user-images.githubusercontent.com/9819174/69726825-98995500-1121-11ea-832a-fefd8e234fb4.png)

**Comment by chrispahm** [comment]
Hi Samarth,

That looks really strange! Can you tell me which version of Atom and Linter Gams you are using?
Best
Christoph

**Comment by samarthiith** [comment]
Atom 1.37.0
Linter-Gams 1.6.2

Yeah, it does. Like I said it's only specifically on this machine that it's a problem. That it's a problem. Maybe, I can try to reinstall atom and linter-gams.
 
thanks

**Comment by chrispahm** [comment]
Hey @samarthiith, 
unfortunately I still have no clue why and how `Gams-View` shows up in the Settings pane. 
![image](https://user-images.githubusercontent.com/20703207/69943903-458b1d80-14e6-11ea-81d7-fabb70b3e80a.png)
As you can see in the above code, the package get's the right pane of a workspace and attaches `Gams-View` to that. Here in our institute we have a couple of Windows machines running different versions of Atom and `linter-gams` and we haven't seen this bug yet. Have you tried installing and uninstalling the plugin?

**Comment by samarthiith** [comment]
Hi,
I uninstalled and installed atom and it works fine now. :)
Thanks,
Samarth
